seed: 42
epochs: 10
batch_size: 128
lr: 0.001
weight_decay: 0.001

model:
  img_size: 32
  patch_size: 4
  num_classes: 10
  embed_dim: 192
  depth: 8
  num_heads: 6
  mlp_ratio: 4.0
  attn_drop: 0.0
  proj_drop: 0.0
  mlp_drop: 0.1
  drop_path: 0.1